CREATE TABLE liveness_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    session_id   VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP    DEFAULT now(),
    updated_at   TIMESTAMP    DEFAULT now(),
    processed_at TIMESTAMP    DEFAULT NULL
);
CREATE INDEX idx_liveness_request_user_id ON liveness_request (user_id);
