CREATE TABLE registration_request (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    code       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    DEFAULT now(),
    updated_at TIMESTAMP    DEFAULT now(),
    expire_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_registration_request_email ON registration_request (email);
