-- "user" é palavra reservada no PostgreSQL, por isso a tabela se chama users.
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    document   VARCHAR(50)  DEFAULT NULL,
    birthdate  DATE         DEFAULT NULL,
    profile    VARCHAR(50)  NOT NULL,
    thumb      VARCHAR(50),
    email      VARCHAR(255) NOT NULL,
    verified   BOOLEAN      DEFAULT FALSE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    DEFAULT now(),
    updated_at TIMESTAMP    DEFAULT now(),
    deleted_at TIMESTAMP    DEFAULT NULL
);

CREATE TABLE user_post (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner      BIGINT      NOT NULL REFERENCES users (id),
    type       INTEGER     NOT NULL,
    link       VARCHAR(50) NOT NULL,
    is_private BOOLEAN     NOT NULL,
    created_at TIMESTAMP   DEFAULT now(),
    updated_at TIMESTAMP   DEFAULT now()
);
CREATE INDEX idx_user_post_owner ON user_post (owner);

CREATE TABLE signature (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber BIGINT    NOT NULL REFERENCES users (id),
    producer   BIGINT    NOT NULL REFERENCES users (id),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),
    expire_at  TIMESTAMP NOT NULL
);
CREATE INDEX idx_signature_subscriber ON signature (subscriber);
CREATE INDEX idx_signature_producer ON signature (producer);

CREATE TABLE wallet (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner   BIGINT         NOT NULL REFERENCES users (id),
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_wallet_owner ON wallet (owner);

CREATE TABLE transaction (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id  BIGINT         NOT NULL REFERENCES wallet (id),
    type       INTEGER        NOT NULL,
    value      NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP      DEFAULT now(),
    updated_at TIMESTAMP      DEFAULT now()
);
CREATE INDEX idx_transaction_wallet_id ON transaction (wallet_id);

CREATE TABLE notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    text       VARCHAR(50) NOT NULL,
    created_at TIMESTAMP   DEFAULT now(),
    readed_at  TIMESTAMP   DEFAULT NULL
);
CREATE INDEX idx_notification_user_id ON notification (user_id);

CREATE TABLE plan (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer   BIGINT         NOT NULL REFERENCES users (id),
    value      NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP      DEFAULT now(),
    updated_at TIMESTAMP      DEFAULT now()
);
CREATE INDEX idx_plan_producer ON plan (producer);
