ALTER TABLE users
    ADD COLUMN highlighted BOOLEAN      DEFAULT NULL,
    ADD COLUMN cover_photo VARCHAR(255) DEFAULT NULL,
    ADD COLUMN tiktok      VARCHAR(255) DEFAULT NULL,
    ADD COLUMN instagram   VARCHAR(255) DEFAULT NULL;
