CREATE TABLE recharge_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users (id),
    value        NUMERIC(19, 2) NOT NULL,
    processed_at TIMESTAMP      DEFAULT NULL,
    created_at   TIMESTAMP      DEFAULT now()
);
CREATE INDEX idx_recharge_request_user_id ON recharge_request (user_id);
